[package]
name = "sauro-examples"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
sauro = { path = "../sauro" }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
sauro-build = { path = "../sauro-build" }
